"""Add edu_orgs_field

Revision ID: 5afe347ca81d
Revises: 2f36d1c8b902
Create Date: 2026-02-24 03:16:53.738570+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afe347ca81d'
down_revision: Union[str, Sequence[str], None] = '2f36d1c8b902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_key', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_organizations_city'), 'educational_organizations', ['city'], unique=False)
    op.create_unique_constraint('uq_club_review_user', 'club_reviews', ['club_id', 'user_id'])
    op.add_column('clubs', sa.Column('edu_org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clubs', 'educational_organizations', ['edu_org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'edu_org_id')
    op.drop_constraint('uq_club_review_user', 'club_reviews', type_='unique')
    op.drop_index(op.f('ix_educational_organizations_city'), table_name='educational_organizations')
    op.drop_table('educational_organizations')
    # ### end Alembic commands ###
