"""A descriptive message for the migration

Revision ID: dfe043e63717
Revises: 
Create Date: 2026-02-25 19:44:28.764668+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfe043e63717'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('description_json', sa.JSON(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_profiles_category'), 'candidate_profiles', ['category'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_city'), 'candidate_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_candidate_profiles_email'), 'candidate_profiles', ['email'], unique=True)
    op.create_table('educational_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_key', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_organizations_city'), 'educational_organizations', ['city'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'CLUB', 'ORGANIZATION', 'INVESTOR', name='user_role'), nullable=False),
    sa.Column('avatar_key', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED', name='webhook_event_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'payload_hash', name='uq_webhook_provider_hash'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_provider_event')
    )
    op.create_index('idx_webhook_status_received', 'webhook_events', ['status', 'received_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.create_table('candidate_profile_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('change_source', sa.Enum('TELEGRAM_BOT', 'WEB', 'SYSTEM', name='profile_change_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'version_no', name='uq_candidate_profile_history_version')
    )
    op.create_index(op.f('ix_candidate_profile_history_candidate_id'), 'candidate_profile_history', ['candidate_id'], unique=False)
    op.create_table('click_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_created_at'), 'click_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_click_events_doc_id'), 'click_events', ['doc_id'], unique=False)
    op.create_index(op.f('ix_click_events_doc_type'), 'click_events', ['doc_type'], unique=False)
    op.create_index(op.f('ix_click_events_user_id'), 'click_events', ['user_id'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('edu_org_id', sa.Integer(), nullable=True),
    sa.Column('logo_key', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['edu_org_id'], ['educational_organizations.id'], ),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_category'), 'clubs', ['category'], unique=False)
    op.create_index(op.f('ix_clubs_city'), 'clubs', ['city'], unique=False)
    op.create_table('investors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_key', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_city'), 'organizations', ['city'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('search_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('top_doc_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_events_created_at'), 'search_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_events_user_id'), 'search_events', ['user_id'], unique=False)
    op.create_table('user_search_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('top_cities', sa.JSON(), nullable=False),
    sa.Column('top_categories', sa.JSON(), nullable=False),
    sa.Column('top_types', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('webhook_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_event_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('http_headers', sa.JSON(), nullable=False),
    sa.Column('remote_addr', sa.String(length=64), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_event_id', 'attempt_no', name='uq_delivery_attempt')
    )
    op.create_index(op.f('ix_webhook_delivery_logs_webhook_event_id'), 'webhook_delivery_logs', ['webhook_event_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'FINISHED', 'CANCELED', name='campaign_status'), nullable=False),
    sa.Column('cover_key', sa.String(length=512), nullable=True),
    sa.Column('gallery_keys', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='check_campaign_dates'),
    sa.CheckConstraint('goal_amount > 0', name='check_campaign_goal_positive'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_club_id'), 'campaigns', ['club_id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('club_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_club', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uq_club_member')
    )
    op.create_index(op.f('ix_club_members_club_id'), 'club_members', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_members_user_id'), 'club_members', ['user_id'], unique=False)
    op.create_table('club_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id')
    )
    op.create_table('club_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('moderation_labels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='check_club_review_score'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'user_id', name='uq_club_review_user')
    )
    op.create_index(op.f('ix_club_reviews_is_approved'), 'club_reviews', ['is_approved'], unique=False)
    op.create_index(op.f('ix_club_reviews_moderation_status'), 'club_reviews', ['moderation_status'], unique=False)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'FINISHED', 'CANCELED', name='competition_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_competition_dates', 'competitions', ['starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_competitions_club_id'), 'competitions', ['club_id'], unique=False)
    op.create_index(op.f('ix_competitions_status'), 'competitions', ['status'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cover_key', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_club_id'), 'news', ['club_id'], unique=False)
    op.create_index('ix_news_club_published', 'news', ['club_id', 'is_published'], unique=False)
    op.create_table('organization_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('avg_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('organization_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('moderation_status', sa.String(length=16), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('moderation_labels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='check_org_review_score'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_review_user')
    )
    op.create_index(op.f('ix_organization_reviews_is_approved'), 'organization_reviews', ['is_approved'], unique=False)
    op.create_index(op.f('ix_organization_reviews_moderation_status'), 'organization_reviews', ['moderation_status'], unique=False)
    op.create_table('tg_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('linked_organization_id', sa.Integer(), nullable=True),
    sa.Column('linked_candidate_id', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_candidate_id'], ['candidate_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_info_telegram_id'), 'tg_info', ['telegram_id'], unique=True)
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('description_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'CLOSED', 'ARCHIVED', name='vacancy_status'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_city'), 'vacancies', ['city'], unique=False)
    op.create_index(op.f('ix_vacancies_organization_id'), 'vacancies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vacancies_position_title'), 'vacancies', ['position_title'], unique=False)
    op.create_index(op.f('ix_vacancies_status'), 'vacancies', ['status'], unique=False)
    op.create_table('competition_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'user_id', name='uq_competition_subscription')
    )
    op.create_index(op.f('ix_competition_subscriptions_competition_id'), 'competition_subscriptions', ['competition_id'], unique=False)
    op.create_index(op.f('ix_competition_subscriptions_user_id'), 'competition_subscriptions', ['user_id'], unique=False)
    op.create_table('employment_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_RESPONSE', 'MUTUAL_MATCHED', 'NOTIFIED', 'CLOSED', 'EXPIRED', 'ARCHIVED', name='employment_match_status'), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'organization_id', 'vacancy_id', name='uq_employment_match_triplet')
    )
    op.create_index(op.f('ix_employment_matches_candidate_id'), 'employment_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_employment_matches_organization_id'), 'employment_matches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employment_matches_status'), 'employment_matches', ['status'], unique=False)
    op.create_index(op.f('ix_employment_matches_vacancy_id'), 'employment_matches', ['vacancy_id'], unique=False)
    op.create_table('employment_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_entity_type', sa.Enum('CANDIDATE', 'ORGANIZATION', name='employment_entity_type'), nullable=False),
    sa.Column('initiator_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_type', sa.Enum('CANDIDATE', 'ORGANIZATION', name='employment_entity_type'), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('LIKE', 'DISLIKE', name='reaction_action'), nullable=False),
    sa.Column('source', sa.Enum('TELEGRAM_BOT', 'WEB', name='reaction_source'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_employment_reaction_idempotency'),
    sa.UniqueConstraint('initiator_entity_type', 'initiator_entity_id', 'target_entity_type', 'target_entity_id', 'vacancy_id', name='uq_employment_reaction_target')
    )
    op.create_index('ix_employment_reactions_target', 'employment_reactions', ['target_entity_type', 'target_entity_id'], unique=False)
    op.create_index(op.f('ix_employment_reactions_vacancy_id'), 'employment_reactions', ['vacancy_id'], unique=False)
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.Enum('DONATION', 'INVESTMENT', 'SPONSORSHIP', name='funding_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELED', name='investment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_investment_amount_positive'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_campaign_id'), 'investments', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_investments_investor_id'), 'investments', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investments_status'), 'investments', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('PAYBOX', 'STRIPE', name='payment_provider'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True),
    sa.Column('checkout_url', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'SUCCESS', 'FAILED', 'CANCELED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_payment_id', name='uq_payment_provider_pid')
    )
    op.create_index('idx_payment_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_investment_id'), 'payments', ['investment_id'], unique=True)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payment_idempotency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope', 'idempotency_key', name='uq_payment_idempotency_user_scope_key')
    )
    op.create_index(op.f('ix_payment_idempotency_user_id'), 'payment_idempotency', ['user_id'], unique=False)
    op.create_table('payment_state_transition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('CREATED', 'PENDING', 'SUCCESS', 'FAILED', 'CANCELED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('to_status', sa.Enum('CREATED', 'PENDING', 'SUCCESS', 'FAILED', 'CANCELED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'USER', 'WEBHOOK', name='payment_actor_type'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_transition_payment_created', 'payment_state_transition_logs', ['payment_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_state_transition_logs_payment_id'), 'payment_state_transition_logs', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_state_transition_logs_payment_id'), table_name='payment_state_transition_logs')
    op.drop_index('idx_payment_transition_payment_created', table_name='payment_state_transition_logs')
    op.drop_table('payment_state_transition_logs')
    op.drop_index(op.f('ix_payment_idempotency_user_id'), table_name='payment_idempotency')
    op.drop_table('payment_idempotency')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_investment_id'), table_name='payments')
    op.drop_index('idx_payment_status_created', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_investments_status'), table_name='investments')
    op.drop_index(op.f('ix_investments_investor_id'), table_name='investments')
    op.drop_index(op.f('ix_investments_campaign_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_employment_reactions_vacancy_id'), table_name='employment_reactions')
    op.drop_index('ix_employment_reactions_target', table_name='employment_reactions')
    op.drop_table('employment_reactions')
    op.drop_index(op.f('ix_employment_matches_vacancy_id'), table_name='employment_matches')
    op.drop_index(op.f('ix_employment_matches_status'), table_name='employment_matches')
    op.drop_index(op.f('ix_employment_matches_organization_id'), table_name='employment_matches')
    op.drop_index(op.f('ix_employment_matches_candidate_id'), table_name='employment_matches')
    op.drop_table('employment_matches')
    op.drop_index(op.f('ix_competition_subscriptions_user_id'), table_name='competition_subscriptions')
    op.drop_index(op.f('ix_competition_subscriptions_competition_id'), table_name='competition_subscriptions')
    op.drop_table('competition_subscriptions')
    op.drop_index(op.f('ix_vacancies_status'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_position_title'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_organization_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_city'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_tg_info_telegram_id'), table_name='tg_info')
    op.drop_table('tg_info')
    op.drop_index(op.f('ix_organization_reviews_moderation_status'), table_name='organization_reviews')
    op.drop_index(op.f('ix_organization_reviews_is_approved'), table_name='organization_reviews')
    op.drop_table('organization_reviews')
    op.drop_table('organization_ratings')
    op.drop_index('ix_news_club_published', table_name='news')
    op.drop_index(op.f('ix_news_club_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_competitions_status'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_club_id'), table_name='competitions')
    op.drop_index('ix_competition_dates', table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_club_reviews_moderation_status'), table_name='club_reviews')
    op.drop_index(op.f('ix_club_reviews_is_approved'), table_name='club_reviews')
    op.drop_table('club_reviews')
    op.drop_table('club_ratings')
    op.drop_index(op.f('ix_club_members_user_id'), table_name='club_members')
    op.drop_index(op.f('ix_club_members_club_id'), table_name='club_members')
    op.drop_table('club_members')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_club_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_webhook_delivery_logs_webhook_event_id'), table_name='webhook_delivery_logs')
    op.drop_table('webhook_delivery_logs')
    op.drop_table('user_search_profiles')
    op.drop_index(op.f('ix_search_events_user_id'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_created_at'), table_name='search_events')
    op.drop_table('search_events')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_city'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('investors')
    op.drop_index(op.f('ix_clubs_city'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_category'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_click_events_user_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_doc_type'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_doc_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_created_at'), table_name='click_events')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_candidate_profile_history_candidate_id'), table_name='candidate_profile_history')
    op.drop_table('candidate_profile_history')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index('idx_webhook_status_received', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_educational_organizations_city'), table_name='educational_organizations')
    op.drop_table('educational_organizations')
    op.drop_index(op.f('ix_candidate_profiles_email'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_city'), table_name='candidate_profiles')
    op.drop_index(op.f('ix_candidate_profiles_category'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
