"""Add edu_org

Revision ID: 9d948be6e289
Revises: c3b4a2d9e6f1
Create Date: 2026-02-23 16:16:43.711925+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d948be6e289'
down_revision: Union[str, Sequence[str], None] = 'c3b4a2d9e6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educational_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_key', sa.String(length=512), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educational_organizations_city'), 'educational_organizations', ['city'], unique=False)
    op.create_unique_constraint('uq_club_review_user', 'club_reviews', ['club_id', 'user_id'])
    op.drop_index(op.f('ix_clubs_edu_org_id'), table_name='clubs')
    op.create_foreign_key(None, 'clubs', 'educational_organizations', ['edu_org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.create_index(op.f('ix_clubs_edu_org_id'), 'clubs', ['edu_org_id'], unique=False)
    op.drop_constraint('uq_club_review_user', 'club_reviews', type_='unique')
    op.drop_index(op.f('ix_educational_organizations_city'), table_name='educational_organizations')
    op.drop_table('educational_organizations')
    # ### end Alembic commands ###
