"""Add new user table

Revision ID: 3366d041159c
Revises: 2f4e7a9b1c22
Create Date: 2026-02-17 07:14:48.015212+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3366d041159c'
down_revision: Union[str, Sequence[str], None] = '2f4e7a9b1c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_club_review_user'), 'club_reviews', type_='unique')
    op.add_column('organization_reviews', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'organization_reviews', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_reviews', type_='foreignkey')
    op.drop_column('organization_reviews', 'author_id')
    op.create_unique_constraint(op.f('uq_club_review_user'), 'club_reviews', ['club_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
